# Generated by Django 5.2.7 on 2025-11-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('loyaltyPoints', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prtoduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oreder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('totalIHT', models.CharField(max_length=100)),
                ('totalITTC', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Tp_IDL.customer')),
                ('prtoduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prtoduct', to='Tp_IDL.prtoduct')),
            ],
        ),
    ]
